### ISSUE TITLE
Explain and ideally remove dependencies on grpcio-tools, cryptography, pyyaml, and grpcio-tools

### ISSUE THREAD

**Issue by simsong** [jcrist/skein#157]
It is unclear to me why skein requires grpcio-tools, cryptography, pyyaml, and grpcio-tools.  `protobuf` seems to be widely used in code, although it seems to be only used for convenience data conversion functions, and not actually by skein itself.

I am attempting to use skein on a disconnected network. The extensive list of dependencies causes problems in two ways:

1. I need to justify each of these dependencies
2. I need to transfer each of these modules, and all of their dependencies, to the disconnected network.

Ideally, the requirements that this installation use grpcio, protobuf, pyyaml and cryptography should be removed.

**Comment by jcrist** [comment]
Skein is a server-client architecture, communicating over grpc using protobuf. These libraries are core to its function - removing them would prevent skein from working completely. I am not about to reimplement message serialization and network communication protocols myself. Cryptography is used to generate the TLS certs. PyYaml is the only one that could possibly be an optional dependency, but is used by 99% of skein users and requiring them to remember to add `pyyaml` to their dependency list is poor UX and not something I'd like to do.

Note that `grpcio-tools` is not a requirement to use skein, only to build it. If you use the wheel from pypi (which could be scp'd and installed locally to your machine, you don't actually need access to pypi) you don't need it.

**Comment by simsong** [comment]
Okay. It would be useful to document this, at least. (It was not clear to me that this was happening.)
From the documentation, it was my impression that Skein ran underneath YARN. Is the Skin client running on every node of the cluster?

**Comment by simsong** [comment]
Ah, so when you write in your documentation that "Skein uses a background driver process written in Java," that is your server, and you communicate it with messages that are serialized using protobufs rather than using a serialization system built in to java?

**Comment by jcrist** [comment]
There are two java processes:

- A `Driver`, which is used to query about running applications, submit new applications, and kill existing applications. This usually runs on the edge node, and is only as long lived as the CLI or python application you're using to submit/interact with the application. This is what `skein.Client()` communicates with.
- An `ApplicationMaster` process that runs in a YARN container during your application. When you submit an application to a YARN cluster, the first thing YARN does is start a user defined process called an "Application Master" in its own container. This process is then responsible for starting/stopping/managing any other containers that the application may need. `skein.ApplicationClient` communicates with this process.

Both of these communicate via grpcio using protobuf. This messaging system was chosen because it's easy to secure, well supported, and language independent. This allows Python to communicate with Java easily, but also allows other language clients to work (e.g. `go`, etc...).

**Comment by jcrist** [comment]
For understanding how YARN operates, you may find this series of blogs useful: https://blog.cloudera.com/blog/2015/09/untangling-apache-hadoop-yarn-part-1/

**Comment by jcrist** [comment]
I think this is resolved(?), feel free to reopen if you have more issues/questions.
