### ISSUE TITLE
Fork support for skein Clients

### ISSUE THREAD

**Issue by nateagr** [jcrist/skein#167]
Hi @jcrist ,

I was using an old version of skein until last week. I've updated skein to use the last version but I ran into problems while executing the same piece of code I was running with the old version of skein. After investigation, I found out that the problem is how skein Clients are instantiated, with grpc_fork_support_disabled(). Do we still need grpc_fork_support_disabled ? I basically run a main which get forked. Each fork create a skein Client by connecting to the global driver.

**Comment by jcrist** [comment]
That was to silence log spam from a warning, that I believe has been quieted in recent versions, so it maybe can be conditionally removed based on grpc version. That said, fork support for grpc has been flaky historically (not sure the current state of things, but they're probably better than they were a year ago).

Why are you using fork here, instead of creating new connections in the child process manually? Grpc's fork support is basically a restart of the library in the child process afaict, so this shouldn't be any more expensive.

```python
# In main process
import skein
skein.Client.start_global_driver()

# In child process
skein.Client.from_global_driver()
```

**Comment by nateagr** [comment]
I do exactly as you've written above. But from_global_driver create a skein Client which creates a stub inside grpc_fork_support_disabled.

**Comment by jcrist** [comment]
I mean do that after the fork, not before. So the main process never creates a stub.

**Comment by nateagr** [comment]
I could but it is not adapted to my case. I end up with forks because I use the multiprocess library to asynchronously run piece of code in parallele to speed up execution time.

**Comment by jcrist** [comment]
I assume you're using `multiprocessing.pool`? In that case, the functions you'd submit might create a client and do some work:

```python
def myfunc(x):
    client = skein.Client.from_global_driver()
    ...

res = pool.apply(myfunc, x)
```

You might also look at the `'forkserver'` start method: https://docs.python.org/3/library/multiprocessing.html?highlight=process#contexts-and-start-methods

That said, the only reason we're disabling things is to stop the log spam in older versions. If you can verify that no longer happens in newer grpcio versions (it's there in 1.16.1, from the commit log it looks like it's fixed in 1.17.0), I'd accept a PR to turn the fork-disabling off for newer grpcio versions.

**Comment by nateagr** [comment]
Hi @jcrist,

I indeed would be interested in a PR. I tried to find the commit you were talking about. Could you please confirm it is this one: https://github.com/grpc/grpc/commit/b88dfc227cd8c9ceeb7797b3265905a93880a077 ? If yes, it has been merged in v1.18.0-pre1.

**Comment by jcrist** [comment]
Yeah, that's it - should be able to skip disabling fork support for versions 1.18.0 and above. Thanks.

**Comment by jcrist** [comment]
Fixed by #168.

**Comment by nateagr** [comment]
Thanks! Would it be possible to make a new release ?

**Comment by jcrist** [comment]
Sure, I can do that. I'll get #169 in as well. Is there anything else you'd need before a release?

**Comment by nateagr** [comment]
Thanks a lot @jcrist. Your last PR will fix our problems.

**Comment by jcrist** [comment]
0.7.1 has been released.
