### ISSUE TITLE
ApplicationClient.shutdown when the app is finished

### ISSUE THREAD

**Issue by superbobry** [jcrist/skein#43]
The current behaviour is to raise `ConnectionError`, but maybe it should be a noop in this case? 

A related question: why have you decided to drop the context manager protocol from `AplicationClient`? It seems useful, since, without it, the app will continue running even if the script which submitted it crashed with an exception. I had to code the following context manager to handle these cases:

```python
@contextmanager
def _shutdown(app: skein.ApplicationClient):
    try:
        yield app
    finally:
        _exc_type, exc_value, _exc_tb = sys.exc_info()
        if isinstance(exc_value, (KeyboardInterrupt, SystemExit)):
            status = "KILLED"
        elif exc_value is not None:
            status = "FAILED"
        else:
            status = "SUCCEEDED"

        try:
            app.shutdown(status)
        except skein.exceptions.ConnectionError:
            pass  # Application already down.
```

**Comment by jcrist** [comment]
> The current behaviour is to raise ConnectionError, but maybe it should be a noop in this case?

I'm not sure. gRPC doesn't provide a good way to differentiate between "no server exists at this address" and "can't reach this address due to network failure". Under most cases if the shutdown operation fails, it's probably because the application has already shutdown, but I can't guarantee that without checking the resource manager, which requires a `skein.Client` instead of a `skein.ApplicationClient` (which may not always be available).

>  why have you decided to drop the context manager protocol from `ApplicationClient`?

You mean from `skein.Application` (now removed). This relates to the above. In Skein we have two remote processes to interact with:

- `skein.Client` interacts with the skein daemon, which communicates with the resource manager
- `skein.ApplicationClient` interacts with the application master

The issue is there are 2 ways to stop an application

- Kill it from the resource manager (an operation on `skein.Client`)
- Ask it to shut itself down (an operation on `skein.ApplicationClient`)

Since a `skein.ApplicationClient` can be created without ever starting a `skein.Client`, we can't query whether the job is still running from the `ApplicationClient` class itself. We *could* interpret all communication failures as "this application is shutdown", but that would be incorrect in the presence of network failure.

Previously the `skein.Application` class existed to provide something that contained both a `skein.Client` (which can verify shutdown in a robust way) and `skein.ApplicationClient` (which does most of the operations). I opted to remove this class in an attempt to simplify the api. Also, while the contextmanager case was nice for quick scripts, it wasn't useful in cases where the application was wrapped in a larger class (as seen in https://github.com/dask/dask-yarn), since the containing class couldn't make use of the `__enter__`/`__exit__` blocks.

I hope that answers your question. If you have suggestions of good api to re-add some of this functionality, I'd welcome it. A few ideas I've had:

- A `shutdown_on` contextmanager method on the `ApplicationClient`, which shutdowns as a failure if an exception is raised, so you can write something like:

```python
app = client.submit_and_connect(spec)
with app.shutdown_on_exception(status='failed'):
    # do stuff
app.shutdown(status='succeeded')
```

- An external `Application` class that users can subclass to create objects that contain `skein.Client` and `skein.ApplicationClient` objects, and will ensure the lifetime of the application is tied to the lifetime of the object (as done in dask-yarn's `YarnCluster`). I'm hesitant to do this though, as every application is different.
