### ISSUE TITLE
Allow to query container states after the app shutdown

### ISSUE THREAD

**Issue by superbobry** [jcrist/skein#67]
I have implemented the following summarization step in tf-yarn:

```
INFO:tf_yarn:
         chief:0  24-8a-07-c4-bb-60:59127  FAILED
     evaluator:0  7c-fe-90-a5-e4-c0:43726  KILLED
            ps:0  e4-1d-2d-4e-e7-80:49801  SUCCEEDED
            ps:1  24-8a-07-77-43-20:60391  SUCCEEDED
            ps:2  7c-fe-90-be-94-90:53100  SUCCEEDED
        worker:0  24-8a-07-c4-b4-c0:53844  KILLED
        worker:1  24-8a-07-77-6b-c0:51395  KILLED
        worker:2  7c-fe-90-a5-e1-b0:42326  KILLED
        worker:3  24-8a-07-bb-bc-d0:55545  KILLED
        worker:4  7c-fe-90-be-c8-c0:41648  KILLED
```

It logs the final state of each skein container. This is mostly helpful for debugging, ie if the application fails, the user would clearly see which containers failed, and which were killed as a result of the application shutdown. At the moment, this feature is implemented in an ad-hoc way via K/V, and therefore sometimes gives false positives (see #66). Do you think it might be useful to make it available in skein itself e.g. make AM record container states and send them over to the daemon on app shutdown?

**Comment by jcrist** [comment]
> Do you think it might be useful to make it available in skein itself e.g. make AM record container states and send them over to the daemon on app shutdown?

Skein so far is designed to make the daemon stateless - no application is tied to a single daemon. I'd prefer to keep it that way, as it means applications can be started, queried, and shutdown without needing a continuous java process.

To solve your specific problem I see a few options:

- Continue to use the k/v store. I'm not sure what you're doing, but I'd have each worker register an owned key on startup, and have some additional process (perhaps on the edge node) watch the event stream for these keys for worker closure. On worker closure I'd update a local store of container state (using `get_containers`). This might fail though if skein shuts down the application before you finish the query.

- Similar to the above, but add an additional service (rather than running on the edge node) in your application to keep track of this state (or push it into one of your existing services). If designed right, this service should never exceed the memory limit (lightweight, don't do work here), and can monitor and report back on the state of the application until some stopping condition (all other containers have completed) before exiting itself. This is probably what I'd do, as some central monitoring service is probably needed for other parts of your application, and moving it off the edge node for long-running-processes has other benefits.

**Comment by superbobry** [comment]
Thanks for sharing your thoughts @jcrist! 

I have considered both possibilities and implemented the first one for now, as it was easier to get right. A separate monitoring service is a good idea and is planned. By the way, I'm slowly working towards making tf-yarn public. The preview version is available [here](https://github.com/criteo/tf-yarn). I would greatly appreciate any feedback you might have!

Closing this issue, since keeping the daemon stateless is a good enough motivation not to proceed with this.

**Comment by jcrist** [comment]
> The preview version is available here. I would greatly appreciate any feedback you might have!

Glad to see it! I'll try to take a look before the end of the week.
